
DROP TABLE IF EXISTS ProjectResumeSection;
DROP TABLE IF EXISTS ProjectEmployee;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS Attachment;
DROP TABLE IF EXISTS Certificate;
DROP TABLE IF EXISTS Skill;
DROP TABLE IF EXISTS Education;
DROP TABLE IF EXISTS Experience;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS BasicInfo;
DROP TABLE IF EXISTS Account;