

package edu.vt.resumemanager.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

// The @Entity annotation designates this class as a JPA Entity POJO class representing the database table Experience.
@Entity
@Data
// Name of the database table represented
@Table(name = "Experience")

@NamedQueries({
        @NamedQuery(name = "Experience.findAll", query = "SELECT e FROM Experience e")
        , @NamedQuery(name = "Experience.findById", query = "SELECT e FROM Experience e WHERE e.id = :id")
        , @NamedQuery(name = "Experience.findByUserId", query = "SELECT e FROM Experience e WHERE e.user = :id")})

public class Experience implements Serializable {
    /*
   ========================================================
   Instance variables representing the attributes (columns)
   of the database table Experience.

   CREATE TABLE Experience
   (
        id int unsigned NOT NULL AUTO_INCREMENT,
        user int unsigned NOT NULL,
        organization varchar(255) DEFAULT NULL,
        title varchar(255) DEFAULT NULL,
        currentlyWorking BOOLEAN NOT NULL DEFAULT 0,
        startDate 	 NOT NULL,
        endDate date NULL,
        responsibilities TEXT DEFAULT NULL,
   );
   ========================================================
    */
    private static final long serialVersionUID = 1L;
    /*
    Primary Key id is auto generated by the system as an Integer value
    starting with 1 and incremented by 1, i.e., 1,2,3,...
    A deleted entity object's primary key number is not reused.
     */
    // id INT UNSIGNED NOT NULL AUTO_INCREMENT
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;

    @Basic(optional = false)
    @Column(name = "user")
    private Integer user;

    // organization VARCHAR(255) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "organization")
    private String organization;

    // title VARCHAR(255) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "title")
    private String title;

    // startDate Date NOT NULL
    @Basic(optional = false)
    @NotNull
    @Column(name = "currentlyWorking")
    private boolean currentlyWorking;

    // startDate Date NOT NULL
    @Basic(optional = false)
    @NotNull
    @Column(name = "startDate")
    private Date startDate;

    // endDate Date NULL
    @Basic(optional = true)
    @Column(name = "endDate")
    private Date endDate;

    // responsibilities TEXT NULL
    @Basic(optional = true)
    @Column(name = "responsibilities")
    private String responsibilities;


}
