
package edu.vt.resumemanager.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

// The @Entity annotation designates this class as a JPA Entity POJO class representing the database table Project.
@Entity
@Data
// Name of the database table represented
@Table(name = "Project")

@NamedQueries({
        @NamedQuery(name = "Project.findAll", query = "SELECT e FROM Project e")
        , @NamedQuery(name = "Project.findById", query = "SELECT e FROM Project e WHERE e.id = :id")
        , @NamedQuery(name = "Project.findByManager", query = "SELECT e FROM Project e WHERE e.manager = :manager")})

public class Project implements Serializable {
    /*
   ========================================================
   Instance variables representing the attributes (columns)
   of the database table Project.

   CREATE TABLE Project
   (
        id int unsigned NOT NULL AUTO_INCREMENT,
        manager int unsigned NOT NULL ,
        name varchar(255) NOT NULL,
        client varchar(255) DEFAULT NULL,
        description TEXT DEFAULT NULL,
        proposal_date DATE DEFAULT NULL,
        status int NOT NULL DEFAULT 1,
   );
   ========================================================
    */
    private static final long serialVersionUID = 1L;
    /*
    Primary Key id is auto generated by the system as an Integer value
    starting with 1 and incremented by 1, i.e., 1,2,3,...
    A deleted entity object's primary key number is not reused.
     */
    // id INT UNSIGNED NOT NULL AUTO_INCREMENT
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;

    // manager VARCHAR(255) NOT NULL
    @Basic(optional = false)
    @Column(name = "manager")
    private Integer manager;

    // name VARCHAR(255) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "name")
    private String name;

    // client VARCHAR(255) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "client")
    private String client;

    // client VARCHAR(255) NOT NULL
    @Basic(optional = true)
    @Column(name = "description")
    private String description;

    // size DECIMAL NOT NULL
    @Basic(optional = false)
    @NotNull
    @Column(name = "proposal_date")
    private Date proposalDate;


    // status int NOT NULL
    @Basic(optional = false)
    @NotNull
    @Column(name = "status")
    private Integer status;

}
