
package edu.vt.resumemanager.entity;

import java.io.Serializable;
import java.sql.Timestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;
import lombok.Data;

// The @Entity annotation designates this class as a JPA Entity POJO class representing the database table template.
@Entity
@Data
// Name of the database table represented
@Table(name = "Template")
public class Template implements Serializable {
    /*
    ========================================================
    Instance variables representing the attributes (columns)
    of the database table template.

    CREATE TABLE Template
    (
        id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
        name VARCHAR(255) NOT NULL,
        content TEXT NOT NULL
    );
    ========================================================
     */
    private static final long serialVersionUID = 1L;
    /*
    Primary Key id is auto generated by the system as an Integer value
    starting with 1 and incremented by 1, i.e., 1,2,3,...
    A deleted entity object's primary key number is not reused.
     */
    // id INT UNSIGNED NOT NULL AUTO_INCREMENT
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;

    // name VARCHAR(32) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "name")
    private String name;


    // content TEXT  NOT NULL
    @Basic(optional = false)
    @NotNull
    @Column(name = "content")
    private String content;

}
